//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Coordinator : Entity<int>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coordinator()
        {
            this.CoordinatorCourses = new HashSet<CoordinatorCourse>();
            this.CoordinatorLocations = new HashSet<CoordinatorLocation>();
            this.CourseProffers = new HashSet<CourseProffer>();
        }
       
        public string CoordinatorName { get; set; }
        public string IDNumber { get; set; }
        public int? IDType { get; set; }
        public int? CountryId { get; set; }
        public virtual Country Country { get; set; }

        public int? CityId { get; set; }
        public virtual City City { get; set; }

        public int? SexId { get; set; }
        public virtual Sex Sex { get; set; }
        public int? NationalityId { get; set; }
        public virtual Nationality Nationality { get; set; }

        public string JawwalNumber { get; set; }
        public string Email { get; set; }
        public byte[] Photograph { get; set; }
        public int? RegistrationCode { get; set; }
        public string RegistrationDate { get; set; }
        public string RegistrationTime { get; set; }
        public int? IsActive { get; set; }
        public int? IsSuspend { get; set; }
        public int? IsDeleted { get; set; }
        public byte[] IDimage { get; set; }
        public int? QualificationDefineId { get; set; }
        public virtual QualificationDefine QualificationDefine { get; set; }
        public string OriginalUploadFileName { get; set; }
        public string UploadFileName { get; set; }
        public string MajorSpecialization { get; set; }
        public string SecondarySpecialization { get; set; }
        public int? GraduationYear { get; set; }
        public string CountryOfGraduation { get; set; }
        public string TheUniversity { get; set; }
        public string Website { get; set; }
        public string CoordinatorName2 { get; set; }
        public string CoordinatorEmail { get; set; }
        public string Headquarters { get; set; }
        public string Describe { get; set; }
        public int? Rooms { get; set; }
        public string Capacity { get; set; }
        public int? AuthorityTypeId { get; set; }
        public virtual AuthorityType AuthorityType { get; set; }
        public string AuthorityNote { get; set; }

        public virtual NumberType NumberType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoordinatorCourse> CoordinatorCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoordinatorLocation> CoordinatorLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseProffer> CourseProffers { get; set; }
    }
}
