//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CoordinatorLocation : Entity<int>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoordinatorLocation()
        {
            this.CSLocations = new HashSet<CSLocation>();
            this.CSLocation_Temp = new HashSet<CSLocation_Temp>();
            this.CourseProffers = new HashSet<CourseProffer>();
            this.LocationRooms = new HashSet<LocationRoom>();
        }
 
        public  int? CountryId { get; set; }
        public virtual Country Country { get; set; }
        public  int? CityId { get; set; }
        public virtual City City { get; set; }
        public string Neighborhood { get; set; }
        public string Street { get; set; }
        public string Building { get; set; }
        public  int? Floor { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public  int? coordinatorId { get; set; }
        public virtual Coordinator Coordinator { get; set; }
        public string note { get; set; }
        public string latlng { get; set; }
        public  bool? valid { get; set; }
        public  int? LocationTypeId { get; set; }
        public virtual LocationType LocationType { get; set; }
        public string GMName { get; set; }
        public  int? GMPhone { get; set; }
        public string classification { get; set; }
        public decimal? Price { get; set; }
        public string LocationEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSLocation> CSLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSLocation_Temp> CSLocation_Temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseProffer> CourseProffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationRoom> LocationRooms { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
