//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course : Entity<int>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CourseTargetedFinals = new HashSet<CourseTargetedFinal>();
            this.Inquiries = new HashSet<Inquiry>();
            this.SectorSupervisorInstitutionDetails = new HashSet<SectorSupervisorInstitutionDetail>();
            this.SelectedLecturers = new HashSet<SelectedLecturer>();
            this.SelectedLecturerTemps = new HashSet<SelectedLecturerTemp>();
            this.TrineeCourseRequests = new HashSet<TrineeCourseRequest>();
            this.CourseProffers = new HashSet<CourseProffer>();
            this.LecturerInterestedCourses = new HashSet<LecturerInterestedCourse>();
            this.LecturerInterestedCourseTemps = new HashSet<LecturerInterestedCourseTemp>();
            this.CourseBookingRequests = new HashSet<CourseBookingRequest>();
            this.ProviderCourses = new HashSet<ProviderCourse>();
            this.OrganizationCourseRequests = new HashSet<OrganizationCourseRequest>();
        }
        
        public string CourseTxt { get; set; }
        public string E_CourseTxt { get; set; }
        public string General_Description { get; set; }
        public string E_General_Description { get; set; }
        public string Detailed_Goal { get; set; }
        public string E_Detailed_Goal { get; set; }
        public string The_main_axis { get; set; }
        public string E_The_main_axis { get; set; }
        public string Targeted { get; set; }
        public int? FieldId { get; set; }
        public virtual Field Field { get; set; }
        public int? SectorId { get; set; }
        public virtual Sector Sector { get; set; }
        public byte[] Course_Img { get; set; }
        public int? InsertCode { get; set; }
        public int? Days { get; set; }
        public int? Hour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTargetedFinal> CourseTargetedFinals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inquiry> Inquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectorSupervisorInstitutionDetail> SectorSupervisorInstitutionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectedLecturer> SelectedLecturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectedLecturerTemp> SelectedLecturerTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrineeCourseRequest> TrineeCourseRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseProffer> CourseProffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LecturerInterestedCourse> LecturerInterestedCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LecturerInterestedCourseTemp> LecturerInterestedCourseTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseBookingRequest> CourseBookingRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderCourse> ProviderCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationCourseRequest> OrganizationCourseRequests { get; set; }
    }
}
