//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CourseBooking : Entity<int>
    {
      
        public string BookingType { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public int? Jawwal { get; set; }
        public string Sex { get; set; }
        public string City { get; set; }
        public string Job { get; set; }
        public string Company { get; set; }
        public string BookingDate { get; set; }
        public string BookingTime { get; set; }
        public int? CourseProfferId { get; set; }
        public string Note { get; set; }
        public string NoteDate { get; set; }
        public string NoteTime { get; set; }
        public int? BookingMax { get; set; }
        public bool? BookRead { get; set; }
    }
}
