//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTargetedFinal : Entity<int>
    {
        
        public int? Num { get; set; }
        public int? InsertCode { get; set; }
        public int? MajorInterestId { get; set; }
        public virtual MajorInterest MajorInterest { get; set; }
        public int? SubInterestId { get; set; }
        public virtual SubInterest SubInterest { get; set; }
        public int? CourseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
