//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSuggestion : Entity<int>
    { 
        public int CourseId { get; set; }
        public string CourseTxt { get; set; }
        public string E_CourseTxt { get; set; }
        public string General_Description { get; set; }
        public string E_General_Description { get; set; }
        public string Detailed_Goal { get; set; }
        public string E_Detailed_Goal { get; set; }
        public string The_main_axis { get; set; }
        public string E_The_main_axis { get; set; }
        public int? Days { get; set; }
        public int? Hour { get; set; }
        public int? LecturerId { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public int? PMPId { get; set; }
        public virtual PMP PMP { get; set; }
        public string LecturerDate { get; set; }
        public string LecturerTime { get; set; }
        public string LecturerNote { get; set; }
        public string PMPDate { get; set; }
        public string PMPTime { get; set; }
        public string PMPNote { get; set; }
        public int? StatusId { get; set; }
        public string OriginalUploadFileName { get; set; }
        public string UploadFileName { get; set; }
        public Nullable<bool> PMPSubmit { get; set; }
        public int? SectorId { get; set; }
        public virtual Sector Sector { get; set; }
        public int? FieldId { get; set; }
        public virtual Field Field { get; set; }
        public int? ProfferStatuId { get; set; }
        public virtual ProfferStatu ProfferStatu { get; set; }
    }
}
