//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CSLocation_Temp : Entity<int>
    {
      
        public int? CourseProfferId { get; set; }
        public virtual CourseProffer CourseProffer { get; set; }
        public int? locId { get; set; }
        public string OriginalUploadFileName { get; set; }
        public string UploadFileName { get; set; }
        public Nullable<decimal> LocPrice { get; set; }
        public int? PriceTypeId { get; set; }
        public virtual PriceType PriceType { get; set; }
        public string note { get; set; }
        public Nullable<bool> selected { get; set; }
        public int? InsertCode { get; set; }
        public int? LocationRoomId { get; set; }
        public virtual LocationRoom LocationRoom { get; set; }
        public  int? CoordinatorLocationId { get; set; }
        public virtual CoordinatorLocation CoordinatorLocation { get; set; }
    
    }
}
