//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class EmailsLog : Entity<int>
    {
       
        public string Send { get; set; }
        public System.DateTime Date { get; set; }
        public string time { get; set; }
        public string SendBy { get; set; }
        public int? SendById { get; set; }
        public string SendTo { get; set; }
        public int? SDay { get; set; }
        public int? SMonth { get; set; }
        public int? SYear { get; set; }
    }
}
