//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Field : Entity<int>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Field()
        {
            this.Courses = new HashSet<Course>();
            this.RegistrationSuggestionCourses = new HashSet<RegistrationSuggestionCourse>();
            this.RegistrationSuggestionCourseTemps = new HashSet<RegistrationSuggestionCourseTemp>();
            this.CourseSuggestions = new HashSet<CourseSuggestion>();
        }
        
        public string FieldTxt { get; set; }
        public string E_FieldTxt { get; set; }
        public int? SectorId { get; set; }
        public virtual Sector Sector { get; set; }
        public string Field_Describe { get; set; }
        public string E_Field_Describe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationSuggestionCourse> RegistrationSuggestionCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationSuggestionCourseTemp> RegistrationSuggestionCourseTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseSuggestion> CourseSuggestions { get; set; }
    }
}
