//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Inquiry : Entity<int>
    {
      
        public string InquiryName { get; set; }
        public string InquiryEmail { get; set; }
        public string InquirySubject { get; set; }
        public string InquiryMsg { get; set; }
        public Nullable<System.DateTime> InquiryDate { get; set; }
        public string InquiryTime { get; set; }
        public Nullable<bool> InquiryRead { get; set; }
        public string InquiryReplay { get; set; }
        public int? InquiryReplayBy { get; set; }
        public Nullable<System.DateTime> InquiryReplayDate { get; set; }
        public string InquiryReplayTime { get; set; }
        public string InquiryType { get; set; }
        public int? CourseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
