//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Lecturer : Entity<int>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lecturer()
        {
            this.DevelopCourses = new HashSet<DevelopCourse>();
            this.LecturerCertificates = new HashSet<LecturerCertificate>();
            this.LecturerQualifications = new HashSet<LecturerQualification>();
            this.LecturerUsers = new HashSet<LecturerUser>();
            this.SelectedLecturers = new HashSet<SelectedLecturer>();
            this.SelectedLecturerTemps = new HashSet<SelectedLecturerTemp>();
            this.TaskProgresses = new HashSet<TaskProgress>();
            this.CourseProffers = new HashSet<CourseProffer>();
            this.LecturerInterestedCourses = new HashSet<LecturerInterestedCourse>();
            this.RegistrationSuggestionCourses = new HashSet<RegistrationSuggestionCourse>();
            this.CourseSuggestions = new HashSet<CourseSuggestion>();
        }
       
        public string LecturerFname { get; set; }
        public string LecturerSname { get; set; }
        public string LecturerTname { get; set; }
        public string LecturerLname { get; set; }
        public string ELecturerFname { get; set; }
        public string ELecturerSname { get; set; }
        public string ELecturerTname { get; set; }
        public string ELecturerLname { get; set; }
        public string IDNumber { get; set; }
        public int? NumberTypeId { get; set; }
        public virtual NumberType NumberType { get; set; }
        public int? CountryId { get; set; }
        public virtual Country Country { get; set; }
        public int? CityId { get; set; }
        public virtual City City { get; set; }
        public string JawwalNumber1 { get; set; }
        public string JawwalNumber2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Fieldofexpertise { get; set; }
        public int? TheNumberOfYears { get; set; }
        public string SubFieldofexpertise { get; set; }
        public int? SubTheNumberOfYears { get; set; }
        public byte[] Photograph { get; set; }
        public int? SexId { get; set; }
        public virtual Sex Sex { get; set; }
        public int? NationalityId { get; set; }
        public int? RegistrationCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSuspend { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string OriginalUploadFileName { get; set; }
        public string UploadFileName { get; set; }
        public string RegistrationDate { get; set; }
        public string RegistrationTime { get; set; }
        public string InvitationCode { get; set; }
        public string RegistrationInvitationCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public int? LecturerId1 { get; set; }
        public virtual Lecturer Lecturer1 { get; set; }
        public virtual ICollection<DevelopCourse> DevelopCourses { get; set; }
        public int? LecturerId2 { get; set; }
        public virtual Lecturer Lecturer2 { get; set; }
        public virtual Nationality Nationality { get; set; }

       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LecturerCertificate> LecturerCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LecturerQualification> LecturerQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LecturerUser> LecturerUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectedLecturer> SelectedLecturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectedLecturerTemp> SelectedLecturerTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskProgress> TaskProgresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseProffer> CourseProffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LecturerInterestedCourse> LecturerInterestedCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationSuggestionCourse> RegistrationSuggestionCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseSuggestion> CourseSuggestions { get; set; }
    }
}
