//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LecturerCertificate : Entity<int>
    {
        
        public byte[] LecturerCertificateImg { get; set; }
        public string LecturerCertificateDate { get; set; }
        public int? RegistrationCode { get; set; }
        public int? LecturerId { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public string LecturerCertificateTital { get; set; }
    
    }
}
