//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LecturerQualification : Entity<int>
    {
        public int? RegistrationCode { get; set; }
        public int? QualificationDefineId { get; set; }
        public virtual QualificationDefine QualificationDefine { get; set; }
        public int? GraduationYear { get; set; }
        public string MajorSpecialization { get; set; }
        public string SecondarySpecialization { get; set; }
        public string TheUniversity { get; set; }
        public string CountryOfGraduation { get; set; }
        public int? LecturerId { get; set; }
    
        public virtual Lecturer Lecturer { get; set; }
    }
}
