//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MyTask : Entity<int>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyTask()
        {
            this.TaskNotes = new HashSet<TaskNote>();
        }
       
        public Nullable<int> TaskFrom { get; set; }
        public Nullable<int> TaskTo { get; set; }
        public string FromType { get; set; }
        public string ToType { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public string TaskTime { get; set; }
        public string TaskPriority { get; set; }
        public string TaskNote { get; set; }
        public byte[] TaskImg { get; set; }
        public string OriginalUploadFileName { get; set; }
        public string UploadFileName { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<int> TaskProgress { get; set; }
        public Nullable<bool> TaskEnd { get; set; }
        public string TaskSubject { get; set; }
        public Nullable<int> TaskPeriod { get; set; }
        public Nullable<int> InsertCode { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<System.DateTime> DateFinsh { get; set; }
        public string TimeFinsh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskNote> TaskNotes { get; set; }
    }
}
