//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationCourseRequestTrainer : Entity<int>
    {
        public int? CRid { get; set; }
        public int? InsertCode { get; set; }
        public int? TrainerId { get; set; }
    
        public virtual Trainer Trainer { get; set; }
        public virtual OrganizationCourseRequest OrganizationCourseRequest { get; set; }
    }
}
