//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrganizationOfficer : Entity<int>
    {
       
        public int? OrganizationId { get; set; }
        public virtual Organization Organization { get; set; }
        public string OfficerName { get; set; }
        public string OfficerJawwal { get; set; }
        public string OfficerEmail { get; set; }
        public string OfficerPassword { get; set; }
        public int? CountryId { get; set; }
        public virtual Country Country { get; set; }
        public int? CityId { get; set; }
        public virtual City City { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string RegistrationTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
    }
}
