//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationCourseRequest : Entity<int>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganizationCourseRequest()
        {
            this.OrganizationCourseRequestTrainers = new HashSet<OrganizationCourseRequestTrainer>();
        }
        public int? OrganizationId { get; set; }
        public virtual Organization Organization { get; set; }
        public int? InsertCode { get; set; }
        public int? CountryId { get; set; }
        public virtual Country Country { get; set; }
        public int? CityId { get; set; }
        public virtual City City { get; set; }
        public string BookingDate { get; set; }
        public string BookingTime { get; set; }
        public int? CourseId { get; set; }
        public virtual Course Course { get; set; }
        public string Note { get; set; }
        public string SuggestedDate { get; set; }
        public string SuggestedTime { get; set; }
        public Nullable<bool> ReqStatus { get; set; }
        public string ReqNote { get; set; }
        public string ReqDate { get; set; }
        public string ReqTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationCourseRequestTrainer> OrganizationCourseRequestTrainers { get; set; }
    }
}
