//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class Provider : Entity<int>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.ProviderCourses = new HashSet<ProviderCourse>();
            this.CourseProffers = new HashSet<CourseProffer>();
            this.ProviderAccreditations = new HashSet<ProviderAccreditation>();
            this.ProviderFields = new HashSet<ProviderField>();
            this.CoordinatorLocations = new HashSet<CoordinatorLocation>();
        }
    
        public string Name { get; set; }
        public string OfficerName { get; set; }
        public string Phone { get; set; }
        public string Jawwal { get; set; }
        public string CallAdress { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSuspend { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string RegistrationDate { get; set; }
        public string RegistrationTime { get; set; }
        public string InvitationCode { get; set; }
        public byte[] Photograph { get; set; }
        public Nullable<int> RegistrationCode { get; set; }
        public byte[] License { get; set; }
        public byte[] CR { get; set; }
        public string AboutUs { get; set; }
        public string FoundationYear { get; set; }
        public string BranchesNumber { get; set; }
        public string CourseArcheived { get; set; }
        public string WorkHoursFrom { get; set; }
        public string WorkHoursTo { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderCourse> ProviderCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseProffer> CourseProffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderAccreditation> ProviderAccreditations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderField> ProviderFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoordinatorLocation> CoordinatorLocations { get; set; }
    }
}
