//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RegistrationSuggestionCourseTemp : Entity<int>
    {
       
        public string CourseTxt { get; set; }
        public int? RegistrationCode { get; set; }
        public int? FieldId { get; set; }
        public virtual Field Field { get; set; }
        public int? SectorId { get; set; }
    
        public virtual Sector Sector { get; set; }
    }
}
