//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SectorSupervisorInstitutionDetail : Entity<int>
    {
      
        public Nullable<int> SectorSupervisorInstitutionId { get; set; }
        public virtual SectorSupervisorInstitution SectorSupervisorInstitution { get; set; }
        public Nullable<int> CourseId { get; set; }
        public virtual Course Course { get; set; }
        public Nullable<int> SectorSupervisorId { get; set; }
    
        public virtual SectorSupervisor SectorSupervisor { get; set; }
    }
}
