//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SectorSupervisorInstitution : Entity<int>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SectorSupervisorInstitution()
        {
            this.SectorSupervisorInstitutionDetails = new HashSet<SectorSupervisorInstitutionDetail>();
        }
       
        public string InstitutionName { get; set; }
        public string InstitutionContact { get; set; }
        public string InstitutionPhone { get; set; }
        public string InstitutionEmail { get; set; }
        public Nullable<int> SectorSupervisorId { get; set; }
    
        public virtual SectorSupervisor SectorSupervisor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectorSupervisorInstitutionDetail> SectorSupervisorInstitutionDetails { get; set; }
    }
}
