//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SectorSupervisor : Entity<int>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SectorSupervisor()
        {
            this.DevelopCourses = new HashSet<DevelopCourse>();
            this.SectorSupervisorCertificates = new HashSet<SectorSupervisorCertificate>();
            this.SectorSupervisorInstitutions = new HashSet<SectorSupervisorInstitution>();
            this.SectorSupervisorInstitutionDetails = new HashSet<SectorSupervisorInstitutionDetail>();
            this.SSectorLists = new HashSet<SSectorList>();
        }
       
        public string SectorSupervisorName { get; set; }
        public string SectorSupervisorEmail { get; set; }
        public byte[] SectorSupervisorImg { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Address { get; set; }
        public Nullable<bool> ReciveRequist { get; set; }
        public string OriginalUploadFileName { get; set; }
        public string UploadFileName { get; set; }
        public string CVOriginalUploadFileName { get; set; }
        public string CVUploadFileName { get; set; }
        public string IDNumber { get; set; }
        public Nullable<int> IDType { get; set; }
        public byte[] IDimage { get; set; }
        public string ContractOriginalUploadFileName { get; set; }
        public string ContractUploadFileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevelopCourse> DevelopCourses { get; set; }
        public virtual NumberType NumberType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectorSupervisorCertificate> SectorSupervisorCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectorSupervisorInstitution> SectorSupervisorInstitutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectorSupervisorInstitutionDetail> SectorSupervisorInstitutionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSectorList> SSectorLists { get; set; }
    }
}
