//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedLecturer : Entity<int>
    {
       
        public Nullable<int> CourseProfferId { get; set; }
        public virtual CourseProffer CourseProffer { get; set; }
        public Nullable<int> LecturerId { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public Nullable<decimal> PriceTemp { get; set; }
        public Nullable<decimal> SelectPrice { get; set; }
        public string LecturerNote { get; set; }
        public Nullable<bool> Selected { get; set; }
        public Nullable<int> CourseId { get; set; }
        public virtual Course Course { get; set; }
        public string UpdateDate { get; set; }
        public string UpdateTime { get; set; }
        public Nullable<bool> Updated { get; set; }
        public Nullable<bool> finish { get; set; }
    
    }
}
