//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Slideshow : Entity<int>
    {
     
        public string SlideshowName { get; set; }
        public string SlideshowBtnName { get; set; }
        public string SlideshowLink { get; set; }
        public Nullable<int> btnTypeId { get; set; }
        public virtual btnType btnType { get; set; }
        public byte[] SlideshowImage { get; set; }
    
    }
}
