//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialTraining : Entity<int>
    {
       
        public string Name { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Jawwal { get; set; }
        public string CourseName { get; set; }
        public string Note { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public Nullable<bool> MsgRead { get; set; }
        public string ReadDate { get; set; }
        public string ReadTime { get; set; }
        public string ReadNote { get; set; }
        public string CourseDate { get; set; }
    }
}
