//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class SSectorList : Entity<int>
    {
    
        public Nullable<int> SectorSupervisorId { get; set; }
        public virtual SectorSupervisor SectorSupervisor { get; set; }
        public Nullable<int> SectorId { get; set; }
    
        public virtual Sector Sector { get; set; }
    }
}
