//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaskProgress : Entity<int>
    {
       
        public string Progress { get; set; }
        public string ProgressDate { get; set; }
        public string ProgressTime { get; set; }
        public Nullable<int> LecturerId { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public Nullable<int> coordinatorId { get; set; }
        public Nullable<int> FinanceId { get; set; }
        public virtual Finance Finance { get; set; }
        public Nullable<int> PMPId { get; set; }
        public virtual PMP PMP { get; set; }
        public Nullable<int> GMId { get; set; }
        public virtual GM GM { get; set; }
        public Nullable<int> CourseProfferId { get; set; }
    
        public virtual CourseProffer CourseProffer { get; set; }
    }
}
