//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaskNote : Entity<int>
    {
       
        public string NoteFrom { get; set; }
        public string FromType { get; set; }
        public Nullable<int> MyTaskId { get; set; }
        public virtual MyTask MyTask { get; set; }
        public Nullable<System.DateTime> NoteDate { get; set; }
        public string NoteTime { get; set; }
        public Nullable<int> FromId { get; set; }
    
    }
}
