//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TrainerInquiry : Entity<int>
    {
      

       
        public Nullable<int> TrainerId { get; set; }
        public virtual Trainer Trainer { get; set; }
        public string InquirySubject { get; set; }
        public string InquiryMsg { get; set; }
        public string InquiryDate { get; set; }
        public string InquiryTime { get; set; }
        public Nullable<bool> InquiryRead { get; set; }
        public string InquiryReplay { get; set; }
        public Nullable<int> InquiryReplayBy { get; set; }
        public string InquiryReplayDate { get; set; }
        public string InquiryReplayTime { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> CourseProfferId { get; set; }
        public virtual CourseProffer CourseProffer { get; set; }
        public Nullable<int> ProviderId { get; set; }
    
    }
}
