//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TrainerInterestedTemp : Entity<int>
    {
      
        public Nullable<int> MajorInterestId { get; set; }
        public virtual MajorInterest MajorInterest { get; set; }
        public Nullable<int> SubInterestId { get; set; }
        public virtual SubInterest SubInterest { get; set; }
        public Nullable<int> RegistrationCode { get; set; }
    
    }
}
