//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Trainer : Entity<int>
    {
        public Trainer()
        {
            this.TrainerInteresteds = new HashSet<TrainerInterested>();
            this.TrainerUsers = new HashSet<TrainerUser>();
            this.RegistrationCourseProffers = new HashSet<RegistrationCourseProffer>();
            this.TrainerOtherInterestedCourses = new HashSet<TrainerOtherInterestedCourse>();
            this.TrineeCourseRequests = new HashSet<TrineeCourseRequest>();
            this.TrainerInterestedCourses = new HashSet<TrainerInterestedCourse>();
            this.OrganizationCourseRequestTrainers = new HashSet<OrganizationCourseRequestTrainer>();
            this.OrganizationCourseRequestTrainerTemps = new HashSet<OrganizationCourseRequestTrainerTemp>();
            this.TrainerInquiries = new HashSet<TrainerInquiry>();
        }
       
        public string TrainerFname { get; set; }
        public string TrainerSname { get; set; }
        public string TrainerTname { get; set; }
        public string TrainerLname { get; set; }
        public string ETrainerFname { get; set; }
        public string ETrainerSname { get; set; }
        public string ETrainerTname { get; set; }
        public string ETrainerLname { get; set; }
        public string IDNumber { get; set; }
        public Nullable<int> NumberTypeId { get; set; }
        public virtual NumberType NumberType { get; set; }
        public Nullable<int> CountryId { get; set; }
        public virtual Country Country { get; set; }
        public Nullable<int> CityId { get; set; }
        public virtual City City { get; set; }
        public Nullable<int> SexId { get; set; }
        public virtual Sex Sex { get; set; }
        public string JawwalNumber1 { get; set; }
        public string JawwalNumber2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public byte[] Photograph { get; set; }
        public Nullable<int> RegistrationCode { get; set; }
        public string RegistrationDate { get; set; }
        public string RegistrationTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSuspend { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public virtual Nationality Nationality { get; set; }
        public Nullable<bool> ProfileUpdate { get; set; }
        public Nullable<int> AddId { get; set; }
        public string AddType { get; set; }
        public string InvitationCode { get; set; }
        public string RegistrationInvitationCode { get; set; }
        public Nullable<int> IsSend { get; set; }
        public string TotalMsg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerInterested> TrainerInteresteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerUser> TrainerUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationCourseProffer> RegistrationCourseProffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerOtherInterestedCourse> TrainerOtherInterestedCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrineeCourseRequest> TrineeCourseRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerInterestedCourse> TrainerInterestedCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationCourseRequestTrainer> OrganizationCourseRequestTrainers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationCourseRequestTrainerTemp> OrganizationCourseRequestTrainerTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerInquiry> TrainerInquiries { get; set; }
    }
}
