//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using Data.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeDelete : Entity<int>
    {
     
        public string Email { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string DeleteDate { get; set; }
        public string DeleteTime { get; set; }
    }
}
